# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui',
# licensing of 'app.ui' applies.
#
# Created: Tue Aug 20 23:15:34 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.combobox_comport = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_comport.setMaximumSize(QtCore.QSize(100, 16777215))
        self.combobox_comport.setObjectName("combobox_comport")
        self.horizontalLayout.addWidget(self.combobox_comport)
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout.addWidget(self.btn_connect)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_connected = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_connected.setFont(font)
        self.label_connected.setObjectName("label_connected")
        self.horizontalLayout_14.addWidget(self.label_connected)
        self.horizontalLayout.addLayout(self.horizontalLayout_14)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.f1_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f1_shortcut_field.setObjectName("f1_shortcut_field")
        self.horizontalLayout_10.addWidget(self.f1_shortcut_field)
        self.btn_f1_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f1_set.setObjectName("btn_f1_set")
        self.horizontalLayout_10.addWidget(self.btn_f1_set)
        self.btn_f1_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f1_delete.setObjectName("btn_f1_delete")
        self.horizontalLayout_10.addWidget(self.btn_f1_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.f2_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f2_shortcut_field.setObjectName("f2_shortcut_field")
        self.horizontalLayout_12.addWidget(self.f2_shortcut_field)
        self.btn_f2_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f2_set.setObjectName("btn_f2_set")
        self.horizontalLayout_12.addWidget(self.btn_f2_set)
        self.btn_f2_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f2_delete.setObjectName("btn_f2_delete")
        self.horizontalLayout_12.addWidget(self.btn_f2_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.f3_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f3_shortcut_field.setObjectName("f3_shortcut_field")
        self.horizontalLayout_3.addWidget(self.f3_shortcut_field)
        self.btn_f3_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f3_set.setObjectName("btn_f3_set")
        self.horizontalLayout_3.addWidget(self.btn_f3_set)
        self.btn_f3_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f3_delete.setObjectName("btn_f3_delete")
        self.horizontalLayout_3.addWidget(self.btn_f3_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.f4_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f4_shortcut_field.setObjectName("f4_shortcut_field")
        self.horizontalLayout_4.addWidget(self.f4_shortcut_field)
        self.btn_f4_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f4_set.setObjectName("btn_f4_set")
        self.horizontalLayout_4.addWidget(self.btn_f4_set)
        self.btn_f4_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f4_delete.setObjectName("btn_f4_delete")
        self.horizontalLayout_4.addWidget(self.btn_f4_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.f5_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f5_shortcut_field.setObjectName("f5_shortcut_field")
        self.horizontalLayout_8.addWidget(self.f5_shortcut_field)
        self.btn_f5_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f5_set.setObjectName("btn_f5_set")
        self.horizontalLayout_8.addWidget(self.btn_f5_set)
        self.btn_f5_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f5_delete.setObjectName("btn_f5_delete")
        self.horizontalLayout_8.addWidget(self.btn_f5_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.f6_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f6_shortcut_field.setObjectName("f6_shortcut_field")
        self.horizontalLayout_13.addWidget(self.f6_shortcut_field)
        self.btn_f6_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f6_set.setObjectName("btn_f6_set")
        self.horizontalLayout_13.addWidget(self.btn_f6_set)
        self.btn_f6_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f6_delete.setObjectName("btn_f6_delete")
        self.horizontalLayout_13.addWidget(self.btn_f6_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.f7_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f7_shortcut_field.setObjectName("f7_shortcut_field")
        self.horizontalLayout_7.addWidget(self.f7_shortcut_field)
        self.btn_f7_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f7_set.setObjectName("btn_f7_set")
        self.horizontalLayout_7.addWidget(self.btn_f7_set)
        self.btn_f7_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f7_delete.setObjectName("btn_f7_delete")
        self.horizontalLayout_7.addWidget(self.btn_f7_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.f8_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f8_shortcut_field.setObjectName("f8_shortcut_field")
        self.horizontalLayout_9.addWidget(self.f8_shortcut_field)
        self.btn_f8_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f8_set.setObjectName("btn_f8_set")
        self.horizontalLayout_9.addWidget(self.btn_f8_set)
        self.btn_f8_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f8_delete.setObjectName("btn_f8_delete")
        self.horizontalLayout_9.addWidget(self.btn_f8_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.f9_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f9_shortcut_field.setObjectName("f9_shortcut_field")
        self.horizontalLayout_6.addWidget(self.f9_shortcut_field)
        self.btn_f9_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f9_set.setObjectName("btn_f9_set")
        self.horizontalLayout_6.addWidget(self.btn_f9_set)
        self.btn_f9_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f9_delete.setObjectName("btn_f9_delete")
        self.horizontalLayout_6.addWidget(self.btn_f9_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.f10_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f10_shortcut_field.setObjectName("f10_shortcut_field")
        self.horizontalLayout_11.addWidget(self.f10_shortcut_field)
        self.btn_f10_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f10_set.setObjectName("btn_f10_set")
        self.horizontalLayout_11.addWidget(self.btn_f10_set)
        self.btn_f10_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f10_delete.setObjectName("btn_f10_delete")
        self.horizontalLayout_11.addWidget(self.btn_f10_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.f11_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f11_shortcut_field.setObjectName("f11_shortcut_field")
        self.horizontalLayout_5.addWidget(self.f11_shortcut_field)
        self.btn_f11_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f11_set.setObjectName("btn_f11_set")
        self.horizontalLayout_5.addWidget(self.btn_f11_set)
        self.btn_f11_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f11_delete.setObjectName("btn_f11_delete")
        self.horizontalLayout_5.addWidget(self.btn_f11_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.f12_shortcut_field = QtWidgets.QLineEdit(self.centralwidget)
        self.f12_shortcut_field.setObjectName("f12_shortcut_field")
        self.horizontalLayout_2.addWidget(self.f12_shortcut_field)
        self.btn_f12_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f12_set.setObjectName("btn_f12_set")
        self.horizontalLayout_2.addWidget(self.btn_f12_set)
        self.btn_f12_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f12_delete.setObjectName("btn_f12_delete")
        self.horizontalLayout_2.addWidget(self.btn_f12_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.btn_setcolor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setcolor.setObjectName("btn_setcolor")
        self.verticalLayout.addWidget(self.btn_setcolor)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Select COM-Port", None, -1))
        self.btn_connect.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.label_connected.setText(QtWidgets.QApplication.translate("MainWindow", "Disconnected", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "F1 Shortcut:  ", None, -1))
        self.btn_f1_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f1_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "F2 Shortcut:  ", None, -1))
        self.btn_f2_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f2_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "F3 Shortcut:  ", None, -1))
        self.btn_f3_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f3_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "F4 Shortcut:  ", None, -1))
        self.btn_f4_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f4_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "F5 Shortcut:  ", None, -1))
        self.btn_f5_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f5_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "F6 Shortcut:  ", None, -1))
        self.btn_f6_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f6_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "F7 Shortcut:  ", None, -1))
        self.btn_f7_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f7_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "F8 Shortcut:  ", None, -1))
        self.btn_f8_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f8_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "F9 Shortcut:  ", None, -1))
        self.btn_f9_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f9_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "F10 Shortcut:", None, -1))
        self.btn_f10_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f10_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "F11 Shortcut:", None, -1))
        self.btn_f11_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f11_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "F12 Shortcut:", None, -1))
        self.btn_f12_set.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.btn_f12_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.btn_setcolor.setText(QtWidgets.QApplication.translate("MainWindow", "Set Color", None, -1))

